
INFO = "logMicroOne"
PRODOTTI = "products"
AMBIENTI = "rooms"
VERSIONE = "version"
ANAGRAFICA = "details"
DATA = "date"
TEMPO = "disinfection_duration"
STATO = "state"
AMBIENTE = "room"
METRI_CUBI = "cubic_meters"
PRODOTTO = "product"
NOME_PRODOTTO = "name"
CONCENTRAZIONE = "concentration"
DATA_SCADENZA = "expiry_date"
LOTTO = "batch_number"
NOME_AMBIENTE = "name"
