# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inserisci_data_scadenza_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inserisci_Data_Scadenza_Window(object):
    def setupUi(self, Inserisci_Data_Scadenza_Window):
        Inserisci_Data_Scadenza_Window.setObjectName("Inserisci_Data_Scadenza_Window")
        Inserisci_Data_Scadenza_Window.resize(480, 315)
        Inserisci_Data_Scadenza_Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancel_btn_ = QtWidgets.QPushButton(Inserisci_Data_Scadenza_Window)
        self.cancel_btn_.setGeometry(QtCore.QRect(410, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn_.setFont(font)
        self.cancel_btn_.setStyleSheet("\n"
"QPushButton:pressed{background-color: rgb(10, 57, 126);}\n"
"QPushButton{\n"
"background-color: rgb(0, 134, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"             \n"
"background-color: rgb(0, 134, 255);\n"
"}")
        self.cancel_btn_.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cancel/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn_.setIcon(icon)
        self.cancel_btn_.setFlat(True)
        self.cancel_btn_.setObjectName("cancel_btn_")
        self.avanti_btn = QtWidgets.QPushButton(Inserisci_Data_Scadenza_Window)
        self.avanti_btn.setGeometry(QtCore.QRect(340, 240, 120, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.avanti_btn.setFont(font)
        self.avanti_btn.setStyleSheet("\n"
"\n"
"QPushButton:pressed{background-color: rgb(10, 57, 126);;}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: rgb(0, 134, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.avanti_btn.setObjectName("avanti_btn")
        self.data_scad_dateEdit = QtWidgets.QDateEdit(Inserisci_Data_Scadenza_Window)
        self.data_scad_dateEdit.setEnabled(True)
        self.data_scad_dateEdit.setGeometry(QtCore.QRect(100, 40, 280, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.data_scad_dateEdit.setFont(font)
        self.data_scad_dateEdit.setTabletTracking(False)
        self.data_scad_dateEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.data_scad_dateEdit.setStyleSheet("QDateEdit::down-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/down_arrow.png);\n"
"     width:50px;\n"
"\n"
"\n"
"     }\n"
"\n"
"\n"
"     QDateEdit::up-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/up_arrow.png);\n"
"     width: 50px;\n"
"     }\n"
"\n"
"\n"
"     QDateEdit {\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"     border-radius:25px;\n"
"border: 5px solid rgb(0, 134, 255);\n"
"\n"
"\n"
"}")
        self.data_scad_dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.data_scad_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2050, 10, 1), QtCore.QTime(0, 0, 0)))
        self.data_scad_dateEdit.setObjectName("data_scad_dateEdit")
        self.keyboard_btn = QtWidgets.QPushButton(Inserisci_Data_Scadenza_Window)
        self.keyboard_btn.setGeometry(QtCore.QRect(10, 235, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.keyboard_btn.setFont(font)
        self.keyboard_btn.setStyleSheet("\n"
"QPushButton:pressed{background-color: rgb(10, 57, 126);}\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"image: url(:/keyboard/res/keyboard.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}")
        self.keyboard_btn.setText("")
        self.keyboard_btn.setFlat(False)
        self.keyboard_btn.setObjectName("keyboard_btn")
        self.label_2 = QtWidgets.QLabel(Inserisci_Data_Scadenza_Window)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.label_2.setStyleSheet("image: url(:/sfondo_data_scadenza/res/pagina_MICROONE_ins_data_scad.png);\n"
"image: url(:/data_scadenza_eng/res/pagina_MICROONE_ins_data_scad_eng.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.cancel_btn_.raise_()
        self.avanti_btn.raise_()
        self.data_scad_dateEdit.raise_()
        self.keyboard_btn.raise_()

        self.retranslateUi(Inserisci_Data_Scadenza_Window)
        self.cancel_btn_.clicked.connect(Inserisci_Data_Scadenza_Window.close)
        QtCore.QMetaObject.connectSlotsByName(Inserisci_Data_Scadenza_Window)

    def retranslateUi(self, Inserisci_Data_Scadenza_Window):
        _translate = QtCore.QCoreApplication.translate
        Inserisci_Data_Scadenza_Window.setWindowTitle(_translate("Inserisci_Data_Scadenza_Window", "Data Scadenza"))
        self.avanti_btn.setText(_translate("Inserisci_Data_Scadenza_Window", "Skip"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inserisci_Data_Scadenza_Window = QtWidgets.QWidget()
    ui = Ui_Inserisci_Data_Scadenza_Window()
    ui.setupUi(Inserisci_Data_Scadenza_Window)
    Inserisci_Data_Scadenza_Window.show()
    sys.exit(app.exec_())
