# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inserisci_data_di_oggi_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inserisci_Data_di_Oggi_Window(object):
    def setupUi(self, Inserisci_Data_di_Oggi_Window):
        Inserisci_Data_di_Oggi_Window.setObjectName("Inserisci_Data_di_Oggi_Window")
        Inserisci_Data_di_Oggi_Window.resize(411, 102)
        Inserisci_Data_di_Oggi_Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5 = QtWidgets.QLabel(Inserisci_Data_di_Oggi_Window)
        self.label_5.setGeometry(QtCore.QRect(-20, -10, 531, 41))
        self.label_5.setStyleSheet("background-color: rgb(0, 140, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Inserisci_Data_di_Oggi_Window)
        self.label.setGeometry(QtCore.QRect(90, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 140, 255);")
        self.label.setObjectName("label")
        self.cancel_btn_ = QtWidgets.QPushButton(Inserisci_Data_di_Oggi_Window)
        self.cancel_btn_.setGeometry(QtCore.QRect(0, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn_.setFont(font)
        self.cancel_btn_.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"                 border-radius:10px;\n"
"             ")
        self.cancel_btn_.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cancel/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn_.setIcon(icon)
        self.cancel_btn_.setObjectName("cancel_btn_")
        self.avanti_btn = QtWidgets.QPushButton(Inserisci_Data_di_Oggi_Window)
        self.avanti_btn.setGeometry(QtCore.QRect(340, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.avanti_btn.setFont(font)
        self.avanti_btn.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.avanti_btn.setObjectName("avanti_btn")
        self.data_oggi_dateTimeEdit = QtWidgets.QDateTimeEdit(Inserisci_Data_di_Oggi_Window)
        self.data_oggi_dateTimeEdit.setEnabled(True)
        self.data_oggi_dateTimeEdit.setGeometry(QtCore.QRect(10, 40, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.data_oggi_dateTimeEdit.setFont(font)
        self.data_oggi_dateTimeEdit.setStyleSheet("QDateTimeEdit::down-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/down_arrow.png);\n"
"     width:50px;\n"
"\n"
"\n"
"     }\n"
"\n"
"\n"
"     QDateTimeEdit::up-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/up_arrow.png);\n"
"     width: 50px;\n"
"     }\n"
"\n"
"\n"
"     QDateTimeEdit {\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"     border-radius:25px;\n"
"border: 5px solid rgb(0,140,255);\n"
"\n"
"\n"
"}")
        self.data_oggi_dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 1), QtCore.QTime(0, 0, 0)))
        self.data_oggi_dateTimeEdit.setObjectName("data_oggi_dateTimeEdit")
        self.keyboard_btn = QtWidgets.QPushButton(Inserisci_Data_di_Oggi_Window)
        self.keyboard_btn.setGeometry(QtCore.QRect(330, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.keyboard_btn.setFont(font)
        self.keyboard_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.keyboard_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/keyboard/res/keyboard_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.keyboard_btn.setIcon(icon1)
        self.keyboard_btn.setObjectName("keyboard_btn")

        self.retranslateUi(Inserisci_Data_di_Oggi_Window)
        self.cancel_btn_.clicked.connect(Inserisci_Data_di_Oggi_Window.close)
        QtCore.QMetaObject.connectSlotsByName(Inserisci_Data_di_Oggi_Window)

    def retranslateUi(self, Inserisci_Data_di_Oggi_Window):
        _translate = QtCore.QCoreApplication.translate
        Inserisci_Data_di_Oggi_Window.setWindowTitle(_translate("Inserisci_Data_di_Oggi_Window", "Data Scadenza"))
        self.label.setText(_translate("Inserisci_Data_di_Oggi_Window", "Inserisci Data di Oggi"))
        self.avanti_btn.setText(_translate("Inserisci_Data_di_Oggi_Window", "Avanti"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inserisci_Data_di_Oggi_Window = QtWidgets.QWidget()
    ui = Ui_Inserisci_Data_di_Oggi_Window()
    ui.setupUi(Inserisci_Data_di_Oggi_Window)
    Inserisci_Data_di_Oggi_Window.show()
    sys.exit(app.exec_())
