# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inserisci_data_di_oggi_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inserisci_Data_di_Oggi_Window(object):
    def setupUi(self, Inserisci_Data_di_Oggi_Window):
        Inserisci_Data_di_Oggi_Window.setObjectName("Inserisci_Data_di_Oggi_Window")
        Inserisci_Data_di_Oggi_Window.resize(480, 315)
        Inserisci_Data_di_Oggi_Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancel_btn_ = QtWidgets.QPushButton(Inserisci_Data_di_Oggi_Window)
        self.cancel_btn_.setGeometry(QtCore.QRect(410, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn_.setFont(font)
        self.cancel_btn_.setStyleSheet("QPushButton:pressed{background-color: rgb(10, 57, 126);}\n"
"QPushButton{\n"
"background-color: rgb(0, 134, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"             \n"
"background-color: rgb(0, 134, 255);\n"
"}")
        self.cancel_btn_.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cancel/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn_.setIcon(icon)
        self.cancel_btn_.setFlat(True)
        self.cancel_btn_.setObjectName("cancel_btn_")
        self.avanti_btn = QtWidgets.QPushButton(Inserisci_Data_di_Oggi_Window)
        self.avanti_btn.setGeometry(QtCore.QRect(340, 240, 120, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.avanti_btn.setFont(font)
        self.avanti_btn.setAutoFillBackground(False)
        self.avanti_btn.setStyleSheet("\n"
" QPushButton:pressed{background-color: rgb(10, 57, 126);;}\n"
"\n"
"\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: rgb(0, 134, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.avanti_btn.setCheckable(False)
        self.avanti_btn.setDefault(False)
        self.avanti_btn.setFlat(False)
        self.avanti_btn.setObjectName("avanti_btn")
        self.data_oggi_dateTimeEdit = QtWidgets.QDateTimeEdit(Inserisci_Data_di_Oggi_Window)
        self.data_oggi_dateTimeEdit.setEnabled(True)
        self.data_oggi_dateTimeEdit.setGeometry(QtCore.QRect(100, 40, 280, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.data_oggi_dateTimeEdit.setFont(font)
        self.data_oggi_dateTimeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.data_oggi_dateTimeEdit.setStyleSheet("QDateTimeEdit::down-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/down_arrow.png);\n"
"     width:50px;\n"
"\n"
"\n"
"     }\n"
"\n"
"\n"
"     QDateTimeEdit::up-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/up_arrow.png);\n"
"     width: 50px;\n"
"     }\n"
"\n"
"\n"
"     QDateTimeEdit {\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"     border-radius:30px;\n"
"border: 5px solid rgb(0,134,255);\n"
"\n"
"\n"
"}")
        self.data_oggi_dateTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.data_oggi_dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 1), QtCore.QTime(0, 0, 0)))
        self.data_oggi_dateTimeEdit.setObjectName("data_oggi_dateTimeEdit")
        self.keyboard_btn = QtWidgets.QPushButton(Inserisci_Data_di_Oggi_Window)
        self.keyboard_btn.setGeometry(QtCore.QRect(10, 235, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.keyboard_btn.setFont(font)
        self.keyboard_btn.setStyleSheet("QPushButton:pressed{background-color: rgb(10, 57, 126);}\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"image: url(:/keyboard/res/keyboard.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}")
        self.keyboard_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/keyboard/res/keyboard_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.keyboard_btn.setIcon(icon1)
        self.keyboard_btn.setObjectName("keyboard_btn")
        self.label = QtWidgets.QLabel(Inserisci_Data_di_Oggi_Window)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.label.setStyleSheet("image: url(:/data_ora_eng/res/pagina_MICROONE_inserisci_data_ora_eng.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label.raise_()
        self.cancel_btn_.raise_()
        self.avanti_btn.raise_()
        self.data_oggi_dateTimeEdit.raise_()
        self.keyboard_btn.raise_()

        self.retranslateUi(Inserisci_Data_di_Oggi_Window)
        self.cancel_btn_.clicked.connect(Inserisci_Data_di_Oggi_Window.close)
        QtCore.QMetaObject.connectSlotsByName(Inserisci_Data_di_Oggi_Window)

    def retranslateUi(self, Inserisci_Data_di_Oggi_Window):
        _translate = QtCore.QCoreApplication.translate
        Inserisci_Data_di_Oggi_Window.setWindowTitle(_translate("Inserisci_Data_di_Oggi_Window", "Data Scadenza"))
        self.avanti_btn.setText(_translate("Inserisci_Data_di_Oggi_Window", "Skip"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inserisci_Data_di_Oggi_Window = QtWidgets.QWidget()
    ui = Ui_Inserisci_Data_di_Oggi_Window()
    ui.setupUi(Inserisci_Data_di_Oggi_Window)
    Inserisci_Data_di_Oggi_Window.show()
    sys.exit(app.exec_())
