# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(480, 320)
        MainWindow.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/res/logo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reg_ambiente_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_ambiente_btn.setGeometry(QtCore.QRect(120, 80, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reg_ambiente_btn.setFont(font)
        self.reg_ambiente_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "      border: 5px solid rgb(0,140,255);\n"
                                            "      border-radius:45px;\n"
                                            "     ")
        self.reg_ambiente_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/save.png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reg_ambiente_btn.setIcon(icon1)
        self.reg_ambiente_btn.setIconSize(QtCore.QSize(32, 32))
        self.reg_ambiente_btn.setObjectName("reg_ambiente_btn")
        self.sel_ambiente_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sel_ambiente_btn.setGeometry(QtCore.QRect(230, 100, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sel_ambiente_btn.setFont(font)
        self.sel_ambiente_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sel_ambiente_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "      border: 5px solid rgb(0,140,255);\n"
                                            "      border-radius:45px;\n"
                                            "     ")
        self.sel_ambiente_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sel_ambiente_btn.setIcon(icon2)
        self.sel_ambiente_btn.setIconSize(QtCore.QSize(50, 50))
        self.sel_ambiente_btn.setObjectName("sel_ambiente_btn")
        self.reg_prodotto_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_prodotto_btn.setGeometry(QtCore.QRect(350, 130, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reg_prodotto_btn.setFont(font)
        self.reg_prodotto_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "      border: 5px solid rgb(0,140,255);\n"
                                            "      border-radius:45px;\n"
                                            "     ")
        self.reg_prodotto_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/prodotto_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reg_prodotto_btn.setIcon(icon3)
        self.reg_prodotto_btn.setIconSize(QtCore.QSize(32, 32))
        self.reg_prodotto_btn.setObjectName("reg_prodotto_btn")
        self.quit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.quit_btn.setGeometry(QtCore.QRect(20, 270, 75, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quit_btn.setFont(font)
        self.quit_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "background-color: rgb(0, 140, 255);\n"
                                    "border-radius:10px;")
        self.quit_btn.setObjectName("quit_btn")
        self.sanifica_label = QtWidgets.QLabel(self.centralwidget)
        self.sanifica_label.setGeometry(QtCore.QRect(40, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sanifica_label.setFont(font)
        self.sanifica_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sanifica_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.sanifica_label.setTextFormat(QtCore.Qt.AutoText)
        self.sanifica_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sanifica_label.setObjectName("sanifica_label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 290, 21, 16))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.sanifica_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sanifica_btn.setGeometry(QtCore.QRect(20, 50, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sanifica_btn.setFont(font)
        self.sanifica_btn.setToolTipDuration(10)
        self.sanifica_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
                                        "      background-color: rgb(255, 255, 255);\n"
                                        "      border-radius:45px;\n"
                                        "      border: 5px solid rgb(0,140,255);\n"
                                        "     ")
        self.sanifica_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/sanifica_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sanifica_btn.setIcon(icon4)
        self.sanifica_btn.setIconSize(QtCore.QSize(32, 32))
        self.sanifica_btn.setObjectName("sanifica_btn")
        self.registra_p_label = QtWidgets.QLabel(self.centralwidget)
        self.registra_p_label.setGeometry(QtCore.QRect(330, 230, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.registra_p_label.setFont(font)
        self.registra_p_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.registra_p_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.registra_p_label.setTextFormat(QtCore.Qt.AutoText)
        self.registra_p_label.setAlignment(QtCore.Qt.AlignCenter)
        self.registra_p_label.setObjectName("registra_p_label")
        self.seleziona_a_label = QtWidgets.QLabel(self.centralwidget)
        self.seleziona_a_label.setGeometry(QtCore.QRect(210, 210, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.seleziona_a_label.setFont(font)
        self.seleziona_a_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.seleziona_a_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.seleziona_a_label.setTextFormat(QtCore.Qt.AutoText)
        self.seleziona_a_label.setAlignment(QtCore.Qt.AlignCenter)
        self.seleziona_a_label.setObjectName("seleziona_a_label")
        self.registra_a_label = QtWidgets.QLabel(self.centralwidget)
        self.registra_a_label.setGeometry(QtCore.QRect(100, 190, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.registra_a_label.setFont(font)
        self.registra_a_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.registra_a_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.registra_a_label.setTextFormat(QtCore.Qt.AutoText)
        self.registra_a_label.setAlignment(QtCore.Qt.AlignCenter)
        self.registra_a_label.setObjectName("registra_a_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MicroOne"))
        self.quit_btn.setText(_translate("MainWindow", "Esci"))
        self.sanifica_label.setText(_translate("MainWindow", "Sanifica"))
        self.label_6.setText(_translate("MainWindow", "v1.0"))
        self.sanifica_btn.setToolTip(_translate("MainWindow", "Clicca per avviare la sanificazione"))
        self.registra_p_label.setText(_translate("MainWindow", "Registra Prodotto"))
        self.seleziona_a_label.setText(_translate("MainWindow", "Seleziona Ambiente"))
        self.registra_a_label.setText(_translate("MainWindow", "Registra Ambiente"))


import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
