# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(486, 327)
        MainWindow.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/res/logo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reg_ambiente_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_ambiente_btn.setGeometry(QtCore.QRect(190, 60, 91, 91))
        self.reg_ambiente_btn.setMaximumSize(QtCore.QSize(91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reg_ambiente_btn.setFont(font)
        self.reg_ambiente_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"      border: 5px solid rgb(0,140,255);\n"
"      border-radius:45px;\n"
"     ")
        self.reg_ambiente_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/save.png.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reg_ambiente_btn.setIcon(icon1)
        self.reg_ambiente_btn.setIconSize(QtCore.QSize(32, 32))
        self.reg_ambiente_btn.setObjectName("reg_ambiente_btn")
        self.reg_prodotto_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_prodotto_btn.setGeometry(QtCore.QRect(360, 110, 91, 91))
        self.reg_prodotto_btn.setMaximumSize(QtCore.QSize(91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reg_prodotto_btn.setFont(font)
        self.reg_prodotto_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"      border: 5px solid rgb(0,140,255);\n"
"      border-radius:45px;\n"
"     ")
        self.reg_prodotto_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/prodotto_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reg_prodotto_btn.setIcon(icon2)
        self.reg_prodotto_btn.setIconSize(QtCore.QSize(32, 32))
        self.reg_prodotto_btn.setObjectName("reg_prodotto_btn")
        self.poweroff_btn = QtWidgets.QPushButton(self.centralwidget)
        self.poweroff_btn.setGeometry(QtCore.QRect(10, 270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.poweroff_btn.setFont(font)
        self.poweroff_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.poweroff_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/poweroff /res/poweroff_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.poweroff_btn.setIcon(icon3)
        self.poweroff_btn.setObjectName("poweroff_btn")
        self.sanifica_label = QtWidgets.QLabel(self.centralwidget)
        self.sanifica_label.setGeometry(QtCore.QRect(40, 210, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.sanifica_label.setFont(font)
        self.sanifica_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sanifica_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.sanifica_label.setTextFormat(QtCore.Qt.AutoText)
        self.sanifica_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sanifica_label.setObjectName("sanifica_label")
        self.sanifica_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sanifica_btn.setGeometry(QtCore.QRect(30, 110, 91, 91))
        self.sanifica_btn.setMaximumSize(QtCore.QSize(91, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sanifica_btn.setFont(font)
        self.sanifica_btn.setToolTipDuration(10)
        self.sanifica_btn.setStyleSheet("color: rgb(0, 0, 0);\n"
"      background-color: rgb(255, 255, 255);\n"
"      border-radius:45px;\n"
"      border: 5px solid rgb(0,140,255);\n"
"     ")
        self.sanifica_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/sanifica_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sanifica_btn.setIcon(icon4)
        self.sanifica_btn.setIconSize(QtCore.QSize(32, 32))
        self.sanifica_btn.setObjectName("sanifica_btn")
        self.registra_p_label = QtWidgets.QLabel(self.centralwidget)
        self.registra_p_label.setGeometry(QtCore.QRect(350, 210, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.registra_p_label.setFont(font)
        self.registra_p_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.registra_p_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.registra_p_label.setTextFormat(QtCore.Qt.AutoText)
        self.registra_p_label.setAlignment(QtCore.Qt.AlignCenter)
        self.registra_p_label.setObjectName("registra_p_label")
        self.registra_a_label = QtWidgets.QLabel(self.centralwidget)
        self.registra_a_label.setGeometry(QtCore.QRect(180, 170, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.registra_a_label.setFont(font)
        self.registra_a_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.registra_a_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.registra_a_label.setTextFormat(QtCore.Qt.AutoText)
        self.registra_a_label.setAlignment(QtCore.Qt.AlignCenter)
        self.registra_a_label.setObjectName("registra_a_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 501, 31))
        self.label.setStyleSheet("background-color: rgb(0, 140, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.serial_label = QtWidgets.QLabel(self.centralwidget)
        self.serial_label.setGeometry(QtCore.QRect(20, 6, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.serial_label.setFont(font)
        self.serial_label.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"color: rgb(0, 0, 0);")
        self.serial_label.setObjectName("serial_label")
        self.settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.settings_btn.setGeometry(QtCore.QRect(400, 0, 61, 31))
        self.settings_btn.setStyleSheet("background-color: rgb(0, 140, 255);")
        self.settings_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/settings/res/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn.setIcon(icon5)
        self.settings_btn.setFlat(True)
        self.settings_btn.setObjectName("settings_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MicroOne"))
        self.sanifica_label.setText(_translate("MainWindow", "Sanifica"))
        self.sanifica_btn.setToolTip(_translate("MainWindow", "Clicca per avviare la sanificazione"))
        self.registra_p_label.setText(_translate("MainWindow", "Registra Prodotto"))
        self.registra_a_label.setText(_translate("MainWindow", "Registra Ambiente"))
        self.serial_label.setText(_translate("MainWindow", "MicroOne-"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
