# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recap_info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recap_info_window(object):
    def setupUi(self, recap_info_window):
        recap_info_window.setObjectName("recap_info_window")
        recap_info_window.resize(480, 320)
        recap_info_window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.download_btn = QtWidgets.QPushButton(recap_info_window)
        self.download_btn.setEnabled(True)
        self.download_btn.setGeometry(QtCore.QRect(340, 240, 120, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.download_btn.setFont(font)
        self.download_btn.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"                 border-radius:10px;\n"
"             ")
        self.download_btn.setObjectName("download_btn")
        self.recap_info_scrollarea = QtWidgets.QScrollArea(recap_info_window)
        self.recap_info_scrollarea.setGeometry(QtCore.QRect(20, 60, 361, 151))
        self.recap_info_scrollarea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recap_info_scrollarea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recap_info_scrollarea.setWidgetResizable(True)
        self.recap_info_scrollarea.setObjectName("recap_info_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 361, 151))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.recap_info_text_edit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.recap_info_text_edit.setGeometry(QtCore.QRect(20, 20, 371, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recap_info_text_edit.sizePolicy().hasHeightForWidth())
        self.recap_info_text_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.recap_info_text_edit.setFont(font)
        self.recap_info_text_edit.setStyleSheet("color: rgb(0, 0, 0);")
        self.recap_info_text_edit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recap_info_text_edit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recap_info_text_edit.setReadOnly(True)
        self.recap_info_text_edit.setObjectName("recap_info_text_edit")
        self.recap_info_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(recap_info_window)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.label_5.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"image: url(:/sfondo_microone/res/pagina_MICROONE.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.cancel_btn = QtWidgets.QPushButton(recap_info_window)
        self.cancel_btn.setEnabled(True)
        self.cancel_btn.setGeometry(QtCore.QRect(390, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"                 border-radius:10px;\n"
"             ")
        self.cancel_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cancel/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn.setIcon(icon)
        self.cancel_btn.setObjectName("cancel_btn")
        self.pushButton = QtWidgets.QPushButton(recap_info_window)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 171, 28))
        self.pushButton.setStyleSheet("image: url(:/microone_logo/res/Microne Bianco.png);\n"
"background-color: rgb(0, 140, 255);")
        self.pushButton.setText("")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.nome_label = QtWidgets.QLabel(recap_info_window)
        self.nome_label.setGeometry(QtCore.QRect(195, 0, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nome_label.setFont(font)
        self.nome_label.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.nome_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nome_label.setObjectName("nome_label")
        self.label_5.raise_()
        self.download_btn.raise_()
        self.recap_info_scrollarea.raise_()
        self.cancel_btn.raise_()
        self.pushButton.raise_()
        self.nome_label.raise_()

        self.retranslateUi(recap_info_window)
        self.cancel_btn.clicked.connect(recap_info_window.close)
        QtCore.QMetaObject.connectSlotsByName(recap_info_window)

    def retranslateUi(self, recap_info_window):
        _translate = QtCore.QCoreApplication.translate
        recap_info_window.setWindowTitle(_translate("recap_info_window", "Info"))
        self.download_btn.setText(_translate("recap_info_window", "Download"))
        self.recap_info_text_edit.setHtml(_translate("recap_info_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Prova Text Edit</span></p></body></html>"))
        self.nome_label.setText(_translate("recap_info_window", "Info"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recap_info_window = QtWidgets.QWidget()
    ui = Ui_recap_info_window()
    ui.setupUi(recap_info_window)
    recap_info_window.show()
    sys.exit(app.exec_())
