# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recap_info_sanifica_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recap_info_sanifica_window(object):
    def setupUi(self, recap_info_sanifica_window):
        recap_info_sanifica_window.setObjectName("recap_info_sanifica_window")
        recap_info_sanifica_window.resize(480, 320)
        recap_info_sanifica_window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recap_info_scrollarea = QtWidgets.QScrollArea(recap_info_sanifica_window)
        self.recap_info_scrollarea.setGeometry(QtCore.QRect(10, 50, 441, 231))
        self.recap_info_scrollarea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recap_info_scrollarea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recap_info_scrollarea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recap_info_scrollarea.setWidgetResizable(True)
        self.recap_info_scrollarea.setObjectName("recap_info_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 231))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.recap_info_text_edit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.recap_info_text_edit.setGeometry(QtCore.QRect(10, 0, 361, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recap_info_text_edit.sizePolicy().hasHeightForWidth())
        self.recap_info_text_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.recap_info_text_edit.setFont(font)
        self.recap_info_text_edit.setStyleSheet("color: rgb(0, 0, 0);")
        self.recap_info_text_edit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recap_info_text_edit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recap_info_text_edit.setReadOnly(True)
        self.recap_info_text_edit.setObjectName("recap_info_text_edit")
        self.recap_info_scrollarea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.recap_info_scrollarea_2.setGeometry(QtCore.QRect(410, 150, 441, 231))
        self.recap_info_scrollarea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recap_info_scrollarea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recap_info_scrollarea_2.setWidgetResizable(True)
        self.recap_info_scrollarea_2.setObjectName("recap_info_scrollarea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 441, 231))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.recap_info_text_edit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.recap_info_text_edit_2.setGeometry(QtCore.QRect(20, 40, 361, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recap_info_text_edit_2.sizePolicy().hasHeightForWidth())
        self.recap_info_text_edit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.recap_info_text_edit_2.setFont(font)
        self.recap_info_text_edit_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.recap_info_text_edit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recap_info_text_edit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recap_info_text_edit_2.setReadOnly(True)
        self.recap_info_text_edit_2.setObjectName("recap_info_text_edit_2")
        self.recap_info_scrollarea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.millilitri_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.millilitri_label.setGeometry(QtCore.QRect(10, 180, 300, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.millilitri_label.setFont(font)
        self.millilitri_label.setStyleSheet("color: rgb(170, 0, 0);")
        self.millilitri_label.setText("")
        self.millilitri_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.millilitri_label.setObjectName("millilitri_label")
        self.recap_info_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.avanti_btn = QtWidgets.QPushButton(recap_info_sanifica_window)
        self.avanti_btn.setGeometry(QtCore.QRect(340, 240, 120, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.avanti_btn.setFont(font)
        self.avanti_btn.setStyleSheet("background-color: rgb(0, 134, 255);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.avanti_btn.setObjectName("avanti_btn")
        self.label_5 = QtWidgets.QLabel(recap_info_sanifica_window)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.label_5.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"image: url(:/sfondo_recap_sanifica/res/pagina_MICROONE_riepilogo_trattamento.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.cancel_btn_ = QtWidgets.QPushButton(recap_info_sanifica_window)
        self.cancel_btn_.setGeometry(QtCore.QRect(410, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn_.setFont(font)
        self.cancel_btn_.setStyleSheet("background-color: rgb(0, 134, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"             \n"
"background-color: rgb(0, 134, 255);")
        self.cancel_btn_.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cancel/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn_.setIcon(icon)
        self.cancel_btn_.setFlat(True)
        self.cancel_btn_.setObjectName("cancel_btn_")
        self.label_5.raise_()
        self.recap_info_scrollarea.raise_()
        self.cancel_btn_.raise_()
        self.avanti_btn.raise_()

        self.retranslateUi(recap_info_sanifica_window)
        self.cancel_btn_.clicked.connect(recap_info_sanifica_window.close)
        QtCore.QMetaObject.connectSlotsByName(recap_info_sanifica_window)

    def retranslateUi(self, recap_info_sanifica_window):
        _translate = QtCore.QCoreApplication.translate
        recap_info_sanifica_window.setWindowTitle(_translate("recap_info_sanifica_window", "Form"))
        self.recap_info_text_edit.setHtml(_translate("recap_info_sanifica_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Prova Text Edit</span></p></body></html>"))
        self.recap_info_text_edit_2.setHtml(_translate("recap_info_sanifica_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Prova Text Edit</p></body></html>"))
        self.avanti_btn.setText(_translate("recap_info_sanifica_window", "Avvia"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recap_info_sanifica_window = QtWidgets.QWidget()
    ui = Ui_recap_info_sanifica_window()
    ui.setupUi(recap_info_sanifica_window)
    recap_info_sanifica_window.show()
    sys.exit(app.exec_())
