# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registra_prodotti.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reg_prodotto_Window(object):
    def setupUi(self, Reg_prodotto_Window):
        Reg_prodotto_Window.setObjectName("Reg_prodotto_Window")
        Reg_prodotto_Window.resize(480, 320)
        Reg_prodotto_Window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nome_label = QtWidgets.QLabel(Reg_prodotto_Window)
        self.nome_label.setGeometry(QtCore.QRect(195, 0, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nome_label.setFont(font)
        self.nome_label.setStyleSheet("background-color: rgb(0, 134, 255);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.nome_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nome_label.setObjectName("nome_label")
        self.nome_textbox = QtWidgets.QLineEdit(Reg_prodotto_Window)
        self.nome_textbox.setGeometry(QtCore.QRect(90, 40, 376, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nome_textbox.setFont(font)
        self.nome_textbox.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 5px solid rgb(0, 134, 255);\n"
"")
        self.nome_textbox.setObjectName("nome_textbox")
        self.data_scad_label = QtWidgets.QLabel(Reg_prodotto_Window)
        self.data_scad_label.setGeometry(QtCore.QRect(130, 0, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.data_scad_label.setFont(font)
        self.data_scad_label.setStyleSheet("color: rgb(0, 0, 0);")
        self.data_scad_label.setObjectName("data_scad_label")
        self.save_btn = QtWidgets.QPushButton(Reg_prodotto_Window)
        self.save_btn.setGeometry(QtCore.QRect(340, 240, 120, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("background-color: rgb(0, 134, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.save_btn.setObjectName("save_btn")
        self.label_5 = QtWidgets.QLabel(Reg_prodotto_Window)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.label_5.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"image: url(:/sfondo_microone/res/pagina_MICROONE.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Reg_prodotto_Window)
        self.label.setGeometry(QtCore.QRect(20, 40, 60, 60))
        self.label.setStyleSheet("image: url(:/icons/res/prodotto_icon.png);\n"
"background-color: rgb(255, 255, 255);\n"
"      border: 5px solid rgb(0, 134, 255);\n"
"      border-radius:30px;\n"
"     ")
        self.label.setText("")
        self.label.setObjectName("label")
        self.cancel_btn_ = QtWidgets.QPushButton(Reg_prodotto_Window)
        self.cancel_btn_.setGeometry(QtCore.QRect(410, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancel_btn_.setFont(font)
        self.cancel_btn_.setStyleSheet("background-color: rgb(0, 140, 255);\n"
"                 color: rgb(255, 255, 255);\n"
"                 border-radius:10px;\n"
"             ")
        self.cancel_btn_.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cancel/res/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn_.setIcon(icon)
        self.cancel_btn_.setFlat(True)
        self.cancel_btn_.setObjectName("cancel_btn_")
        self.concentrazione_label = QtWidgets.QLabel(Reg_prodotto_Window)
        self.concentrazione_label.setGeometry(QtCore.QRect(330, 110, 130, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concentrazione_label.sizePolicy().hasHeightForWidth())
        self.concentrazione_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.concentrazione_label.setFont(font)
        self.concentrazione_label.setStyleSheet("color: rgb(0, 134, 255);")
        self.concentrazione_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.concentrazione_label.setObjectName("concentrazione_label")
        self.concentrazione_spinBox = QtWidgets.QSpinBox(Reg_prodotto_Window)
        self.concentrazione_spinBox.setGeometry(QtCore.QRect(161, 110, 158, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.concentrazione_spinBox.setFont(font)
        self.concentrazione_spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.concentrazione_spinBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.concentrazione_spinBox.setStyleSheet("QSpinBox::down-button {\n"
"\n"
"                    image: url(:/arrows/res/down_arrow.png);\n"
"                    width:50px;\n"
"                    }\n"
"\n"
"\n"
"                    QSpinBox::up-button {\n"
"\n"
"                    image: url(:/arrows/res/up_arrow.png);\n"
"                    width: 50px;\n"
"                    }\n"
"\n"
"\n"
"                    QSpinBox {\n"
"                    color: rgb(0, 0, 0);\n"
"                \n"
"    background-color: rgb(255, 255, 255);\n"
"border: 5px solid rgb(0, 134, 255);\n"
"                    border-radius:30px;\n"
"\n"
"\n"
"                    }\n"
"                ")
        self.concentrazione_spinBox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.concentrazione_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.concentrazione_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.concentrazione_spinBox.setMinimum(1)
        self.concentrazione_spinBox.setMaximum(3000)
        self.concentrazione_spinBox.setSingleStep(1)
        self.concentrazione_spinBox.setProperty("value", 1)
        self.concentrazione_spinBox.setObjectName("concentrazione_spinBox")
        self.data_scad_dateEdit = QtWidgets.QDateEdit(Reg_prodotto_Window)
        self.data_scad_dateEdit.setEnabled(False)
        self.data_scad_dateEdit.setGeometry(QtCore.QRect(110, -30, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.data_scad_dateEdit.setFont(font)
        self.data_scad_dateEdit.setStyleSheet("QDateEdit::down-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/down_arrow.png);\n"
"     width:50px;\n"
"\n"
"\n"
"     }\n"
"\n"
"\n"
"     QDateEdit::up-button {\n"
"\n"
"\n"
"     image: url(:/arrows/res/up_arrow.png);\n"
"     width: 50px;\n"
"     }\n"
"\n"
"\n"
"     QDateEdit {\n"
"     color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"     border-radius:25px;\n"
"border: 5px solid rgb(0,140,255);\n"
"\n"
"\n"
"}")
        self.data_scad_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 10, 1), QtCore.QTime(0, 0, 0)))
        self.data_scad_dateEdit.setObjectName("data_scad_dateEdit")
        self.keyboard_btn = QtWidgets.QPushButton(Reg_prodotto_Window)
        self.keyboard_btn.setGeometry(QtCore.QRect(10, 235, 120, 70))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.keyboard_btn.setFont(font)
        self.keyboard_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/keyboard/res/keyboard.png);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.keyboard_btn.setText("")
        self.keyboard_btn.setObjectName("keyboard_btn")
        self.concentrazione_label_2 = QtWidgets.QLabel(Reg_prodotto_Window)
        self.concentrazione_label_2.setGeometry(QtCore.QRect(396, 110, 31, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concentrazione_label_2.sizePolicy().hasHeightForWidth())
        self.concentrazione_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.concentrazione_label_2.setFont(font)
        self.concentrazione_label_2.setStyleSheet("color: rgb(0, 134, 255);")
        self.concentrazione_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.concentrazione_label_2.setObjectName("concentrazione_label_2")
        self.data_scad_dateEdit.raise_()
        self.data_scad_label.raise_()
        self.label_5.raise_()
        self.nome_textbox.raise_()
        self.save_btn.raise_()
        self.label.raise_()
        self.cancel_btn_.raise_()
        self.concentrazione_label.raise_()
        self.concentrazione_spinBox.raise_()
        self.keyboard_btn.raise_()
        self.nome_label.raise_()
        self.concentrazione_label_2.raise_()

        self.retranslateUi(Reg_prodotto_Window)
        self.cancel_btn_.clicked.connect(Reg_prodotto_Window.close)
        QtCore.QMetaObject.connectSlotsByName(Reg_prodotto_Window)

    def retranslateUi(self, Reg_prodotto_Window):
        _translate = QtCore.QCoreApplication.translate
        Reg_prodotto_Window.setWindowTitle(_translate("Reg_prodotto_Window", "Registra Prodotto"))
        self.nome_label.setText(_translate("Reg_prodotto_Window", "Inserisci Nome Prodotto"))
        self.data_scad_label.setText(_translate("Reg_prodotto_Window", "Inserisci data di scadenza"))
        self.save_btn.setText(_translate("Reg_prodotto_Window", "Salva"))
        self.concentrazione_label.setText(_translate("Reg_prodotto_Window", "ml/m"))
        self.concentrazione_label_2.setText(_translate("Reg_prodotto_Window", "3"))
import img_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Reg_prodotto_Window = QtWidgets.QWidget()
    ui = Ui_Reg_prodotto_Window()
    ui.setupUi(Reg_prodotto_Window)
    Reg_prodotto_Window.show()
    sys.exit(app.exec_())
